### ISSUE TITLE
How to make service resolvers for apollo?

### ISSUE THREAD

**Issue by MercerMorning** [axtiva/flexible-graphql-bundle#12]
Hi! How to make service resolvers for apollo? I dont get it after php bin/console flexible_graphql:generate-type-registry command

**Comment by bpteam** [comment]
Hello Mercer!

They should be generated in the folder that you specified in the bundle config by path flexible_graphql.dir

```yaml
# content of config/packages/flexible_graphql.yaml
flexible_graphql:
...
  dir: '%kernel.project_dir%/src/GraphQL/' # path where it will be they save files
...
```

thank you for being interested in our library

**Comment by bpteam** [comment]
if you are asking about the _service resolver, then it is generated automatically, but for this you need to enable `federation` graph mode in bundle config:

```yaml
# content of config/packages/flexible_graphql.yaml
flexible_graphql:
...
  schema_type: federation # type of schema generation. Default is `graphql` or optional is `federation` for apollo federation support 
...  
```
